######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 15 23:03:32 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml

# Input
HEADERS += nlptest.h
SOURCES += nlptest.cpp


SOURCES += \
    ../src/numericalattribute.cpp \
    ../src/stringattribute.cpp \
    ../src/relationship.cpp \
    ../src/critique.cpp \
    ../src/offer.cpp \
    ../src/valueattribute.cpp \
    ../src/critiquerecommender.cpp \
    ../src/recomment.cpp \
    ../src/attributefactory.cpp \
    ../src/compoundattribute.cpp

HEADERS += \
    ../src/attribute.h \
    ../src/numericalattribute.h \
    ../src/stringattribute.h \
    ../src/relationship.h \
    ../src/critique.h \
    ../src/offer.h \
    ../src/valueattribute.h \
    ../src/critiquerecommender.h \
    ../src/recomment.h \
    ../src/attributefactory.h \
    ../src/compoundattribute.h

